name: generate 3d contribution graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-3d-contrib
          if ! git diff --cached --quiet; then
            git commit -m "chore: regen 3d contrib"
            git push
          fi
